name: Delete Branch on Jira Task Done

on:
  repository_dispatch:
    types: [jira-task-done]

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all remote branches
        run: git fetch --all

      - name: set url with pat 
        run: git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Find and delete matching branch corresponding to Jira ticket
        run: |
          # Define the branch pattern using the Jira issue key (e.g., SCRUM-1-*)
          BRANCH_PATTERN="${{ github.event.client_payload.issueKey }}-*"
          
          # List all remote branches and search for a match using the pattern
          MATCHING_BRANCH=$(git branch -r | grep "origin/${BRANCH_PATTERN}" | head -n 1)
          
          if [ -n "$MATCHING_BRANCH" ]; then
            # Remove 'origin/' from the branch name, ensuring no leading/trailing spaces
            BRANCH_NAME="${MATCHING_BRANCH#origin/}"
            BRANCH_NAME=$(echo "$BRANCH_NAME" | xargs)
      
            # Delete the remote branch
            git push origin --delete "$BRANCH_NAME"
            echo "Successfully deleted branch: $BRANCH_NAME"
          else
            echo "No matching branch found for pattern: $BRANCH_PATTERN"
          fi
